export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_REQUEST";

export const ADMIN_GET_USERS_DATA_REQUEST = "ADMIN_GET_USERS_DATA_REQUEST";
export const ADMIN_GET_USERS_DATA_SUCCESS = "ADMIN_GET_USERS_DATA_SUCCESS";
export const ADMIN_GET_USERS_DATA_FAIL = "ADMIN_GET_USERS_DATA_FAIL";