export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_GET_USERS_DATA_REQUEST = "ADMIN_GET_USERS_DATA_REQUEST";
export const ADMIN_GET_USERS_DATA_SUCCESS = "ADMIN_GET_USERS_DATA_SUCCESS";
export const ADMIN_GET_USERS_DATA_FAIL = "ADMIN_GET_USERS_DATA_FAIL";
export const ADMIN_UPDATE_USERS_LIST = "ADMIN_UPDATE_USERS_LIST";

export const ADMIN_ADD_EMPLOYEE_REQUEST = "ADMIN_ADD_EMPLOYEE_REQUEST";
export const ADMIN_ADD_EMPLOYEE_SUCCESS = "ADMIN_ADD_EMPLOYEE_SUCCESS";
export const ADMIN_ADD_EMPLOYEE_FAIL = "ADMIN_ADD_EMPLOYEE_FAIL";

export const ADMIN_EDIT_EMPLOYEE_REQUEST = "ADMIN_EDIT_EMPLOYEE_REQUEST";
export const ADMIN_EDIT_EMPLOYEE_SUCCESS = "ADMIN_EDIT_EMPLOYEE_SUCCESS";
export const ADMIN_EDIT_EMPLOYEE_FAIL = "ADMIN_EDIT_EMPLOYEE_FAIL";

export const ADMIN_DELETE_EMPLOYEE_REQUEST = "ADMIN_DELETE_EMPLOYEE_REQUEST";
export const ADMIN_DELETE_EMPLOYEE_SUCCESS = "ADMIN_DELETE_EMPLOYEE_SUCCESS";
export const ADMIN_DELETE_EMPLOYEE_FAIL = "ADMIN_DELETE_EMPLOYEE_FAIL";

export const GET_SINGLE_EMPLOYEE_REQUEST = "GET_SINGLE_EMPLOYEE_REQUEST";
export const GET_SINGLE_EMPLOYEE_SUCCESS = "GET_SINGLE_EMPLOYEE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_FAIL= "GET_SINGLE_EMPLOYEE_FAIL";